### ISSUE TITLE
Index out of bounds in buildFinished action

### ISSUE THREAD

**Issue by ZacSweers** [gradle/common-custom-user-data-gradle-plugin#176]
Since introducing this plugin to our build, we keep seeing this warning printed at the end of builds on CI, but aren't able to get a trace from gradle or indication of where it's coming from. Let me know what I can do to help debug.

```
WARNING: Error invoking build scan buildFinished action
	Index -1 out of bounds for length 18
```

**Comment by runningcode** [comment]
Thanks, could you try running this build with `--stacktrace` and sending us the logs?

**Comment by ZacSweers** [comment]
Looks like it's not this plugin, sorry for the false alarm!

```

WARNING: Error invoking build scan buildFinished action
--
  | java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 18
  | at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
  | at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
  | at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
  | at java.base/java.util.Objects.checkIndex(Objects.java:385)
  | at java.base/java.util.ArrayList.get(ArrayList.java:427)
  | at io.github.cdsap.kotlinprocess.parser.JStatData.getCollector(JStatData.kt:59)
  | at io.github.cdsap.kotlinprocess.parser.JStatData.process(JStatData.kt:25)
  | at io.github.cdsap.kotlinprocess.ConsolidateProcesses.consolidate(ConsolidateProcesses.kt:14)
  | at io.github.cdsap.kotlinprocess.InfoKotlinProcessPlugin$buildScanReporting$1.execute(InfoKotlinProcessPlugin.kt:38)
  | at io.github.cdsap.kotlinprocess.InfoKotlinProcessPlugin$buildScanReporting$1.execute(InfoKotlinProcessPlugin.kt:37)
  | at com.gradle.enterprise.gradleplugin.internal.extension.a$5.a(SourceFile:213)
  | at com.gradle.enterprise.gradleplugin.internal.extension.a$5.accept(SourceFile:210)
  | at com.gradle.scan.plugin.internal.q.b.b.a(SourceFile:45)
  | at java.base/java.lang.Iterable.forEach(Iterable.java:75)

```
